# Header

menu:
  Home: /
#  Pandas: /categories/pandas/
#  OSS: / categories/oss
  About: /2020/04/20/About-PySport/


# SubNav
subnav:
  github: "https://github.com/pysport"
#  weibo: "#"
#  rss: "#"
#  zhihu: "#"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  #mail: "mailto:litten225@qq.com"
  #facebook: "#"
  #google: "#"
  twitter: "https://twitter.com/PySportOrg"
  #linkedin: "#"

rss: /atom.xml


# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: 'More'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
google_analytics: ''
favicon: /images/logo.png

#你的头像url
avatar: /images/logo.svg

footer: Sponsored by <a href="https://teamtv.co.uk/" target="_blank" noopener><img border="0" height="20px" src="https://teamtv.nl/wp-content/uploads/Asset-2@2x.png" /></a> | <a href="mailto:koen@teamtv.nl">join us</a>


# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: false
#  friends: '友链'
#  aboutme: '关于我'

friends:
  友情链接1: http://localhost:4000/
  友情链接2: http://localhost:4000/
  友情链接3: http://localhost:4000/
  友情链接4: http://localhost:4000/
  友情链接5: http://localhost:4000/
  友情链接6: http://localhost:4000/

aboutme: 很惭愧<br><br>只做了一点微小的工作<br>谢谢大家
